couple of tighter things

diff --git a/.github/actions/cleanup-runner/action.yml b/.github/actions/cleanup-runner/action.yml
--- a/.github/actions/cleanup-runner/action.yml
+++ b/.github/actions/cleanup-runner/action.yml
@@ -12,7 +12,7 @@ inputs:
     description: GCP Zone
     required: true
   instance_label:
-    description: Label to identify the instance
+    description: Label to identify the inscompositetance
     required: true
 
 runs:
@@ -20,10 +20,16 @@ runs:
   steps:
     - id: auth
       shell: bash
-      run: echo '${{ inputs.service_account_key }}' | gcloud --project  '${{ inputs.project_id }}' --quiet auth activate-service-account --key-file - &>/dev/null
+      run: echo '${{ inputs.service_account_key }}' | gcloud --project  '${{ inputs.project_id }}' --quiet auth activate-service-account --key-file - >/dev/null 2>&1
     - id: get-runner-id
       shell: bash
-      run: echo "runner_id=$(gcloud compute instances list --filter=labels=${{ inputs.instance_label }} | awk '{print $1}' | tail +2)" >> $GITHUB_OUTPUT
+      run: |
+        runner_id=$(gcloud compute instances list --filter=labels=${{ inputs.instance_label }} | awk '{print $1}' | tail +2)
+        if [ -z "$runner_id" ]; then
+          echo "Instance with label ${{ inputs.instance_label }} not found"
+          exit 1
+        fi
+        echo "runner_id=$runner_id" >> $GITHUB_OUTPUT
     - id: kill-runner
       shell: bash
       run: gcloud compute instances delete ${{ steps.get-runner-id.outputs.runner_id }} --zone=${{ inputs.zone }} --quiet
